version: '3.9'
services:
  py_node:
    image: python3:11
    environment:
      - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
    build:
      context: .
      dockerfile: docker/py_node.dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    privileged: true
    command: bash -c "chown -R vscode:vscode /app &&
                     sleep infinity"
