version: '3.9'
services:
  py_node:
    image: python3:11
    environment:
      - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
    build:
      context: .
      dockerfile: docker/py_node.dockerfile
    env_file:
      - .env
    volumes:
      - C:/py_pdf/:/app
    privileged: true
    command: bash -c "python3 -m venv venv &&
                     source venv/bin/activate &&
                     pip install -r src/requirements.txt &&
                     chown -R vscode:vscode /app &&
                     sleep infinity"
    #command: bash -c "sleep infinity"